algo = input("Digite algo: ")
print("O time primitivo desse valor é {}".format(type(algo)))
print("Só tem espaços? {}".format(algo.isspace()))
print("É um número? {}".format(algo.isnumeric()))
print("É alfabético? {}".format(algo.isalpha()))
print("É alfanumérico? {}".format(algo.isalnum()))
print("Estpa em maiúsculas? {}".format(algo.isupper()))
print("Está em minúsculas? ".format(algo.islower()))
''' Capitalizado quer dizer que esta com a primeira maiuscula '''
print("Está caputalizada? {}".format(algo.istitle()))