nome = str(input("Digite seu nome completo: "))
print("Muito prazer em te conhecer!")
snome = nome.split()
print("Seu primeiro nome é {}".format(snome[0]))
print("Seu último nome é {}".format(snome[-1]))
