times = (("Flamengo", "São Paulo", "Corinthians", "Fluminense", "Internacional", "Sport", "Cruzeiro", "Atlético-MG", "Grêmio", "Palmeiras", "Vasco", "América-MG", "Botafogo", "Chapecoense", "Vitória", "Bahia", "Santos", "Atlético-PR", "Ceará", "Paraná"))
print("-="*20)
print(f'Lista de times do Brasileirão: {times}')
print("-="*20)
print(f'Os 5 primeiros times são: {times[0:5]}')
print("-="*20)
print(f'Os 4 primeiros times são: {times[-4:]}')
print("-="*20)
print(f'Os times em ordem alfabetica ficam: {sorted(times)}')